apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: wanderlust
type: Opaque
stringData:
  JWT_SECRET: mysecretkey

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: wanderlust
type: Opaque
stringData:
  mongo-root-username: admin
  mongo-root-password: secret123