backend:
  name: wanderlust-backend
  namespace: wanderlust
  replicas: 2
  app: backend
  image: 562404438689.dkr.ecr.us-east-1.amazonaws.com/wanderlust-backend
  port: 5000
  nodeport: 30001
  path: /health
  targetPort: 5000
  tag: v1
  imagePullPolicy: always

frontend:
  name: wanderlust-frontend
  namespace: wanderlust
  replicas: 2
  app: frontend
  image: 562404438689.dkr.ecr.us-east-1.amazonaws.com/wanderlust-frontend
  port: 80
  nodeport: 30000
  path: /
  targetPort: 80
  tag: v1
  imagePullPolicy: always

mongodb:
  name: mongodb
  dbName: wanderlust
  serviceName: mongodb-sc
  namespace: wanderlust
  replicas: 2
  app: mongodb
  image: mongo:7.0
  port: 27017
  database: starbucks
  storageClassName: standard
  secretName: mongodb-secret
  pullPolicy: IfNotPresent # Kind built-in storage class
  storage:
    size: 1Gi
  #secret:
  #name: mongo-secret
  #namespace: starbucks-ns
  #app: mongo-express
  #mongoUser: YWRtaW4K
  #mongoPassword: cGFzc3dvcmQxMjMK

secret:
  name: mongodb-secret
  jwtSecret: mysecretkey
  mongoUser: admin
  mongoPassword: secret123

redis:
  name: redis
  namespace: wanderlust
  app: redis
  serviceName: redis
  replicas: 1
  image: redis:7 # matched to your docker-compose
  pullPolicy: IfNotPresent
  port: 6379
  storageClassName: standard
  storageSize: 512Mi
