pipeline {
    agent any

    parameters {
        choice(
            name: 'MODULE',
            choices: ['ecr', 'vpc', 'eks'],
            description: 'Select Terraform module'
        )

        string(
            name: 'wenderlust',
            defaultValue: 'dev',
            description: 'Environment'
        )

        choice(
            name: 'terraform_action',
            choices: ['plan', 'apply', 'destroy'],
            description: 'Terraform Action'
        )
    }

    environment {
        AWS_REGION = 'us-east-1'
    }

    stages {

        stage('Preparing') {
            steps {
                echo "Preparing..."
            }
        }

        stage('Git Checkout') {
            steps {
                git(
                    url: 'https://github.com/gopi-ganesan/wanderlust-app.git',
                    branch: 'main',
                    credentialsId: 'github-creds'
                )
            }
        }

        stage('Set Terraform Directory') {
            steps {
                script {
                    env.TERRAFORM_DIR = "devops-project-o2/Infrastructure/${params.MODULE}"
                    echo "Terraform Directory: ${env.TERRAFORM_DIR}"
                }
            }
        }

        stage('Debug Workspace') {
            steps {
                sh '''
                    echo "Current Directory:"
                    pwd

                    echo "Terraform Directory:"
                    ls -la ${TERRAFORM_DIR}

                    echo "Terraform Files:"
                    find ${TERRAFORM_DIR} -name "*.tf"
                '''
            }
        }

        stage('Terraform Init') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-credentials',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {
                    sh '''
                        export AWS_DEFAULT_REGION=${AWS_REGION}

                        terraform -chdir=${TERRAFORM_DIR} init
                    '''
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-credentials',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {
                    sh '''
                        export AWS_DEFAULT_REGION=${AWS_REGION}

                        terraform -chdir=${TERRAFORM_DIR} validate
                    '''
                }
            }
        }

        stage('Terraform Action') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-credentials',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {

                    script {

                        if (params.terraform_action == 'plan') {

                            sh """
                                export AWS_DEFAULT_REGION=${AWS_REGION}

                                terraform -chdir=${TERRAFORM_DIR} plan \
                                -var="environment=${params.environment}" \
                                -out=tfplan
                            """
                        }

                        else if (params.terraform_action == 'apply') {

                            sh """
                                export AWS_DEFAULT_REGION=${AWS_REGION}

                                terraform -chdir=${TERRAFORM_DIR} apply \
                                -var="environment=${params.environment}" \
                                -auto-approve
                            """
                        }

                        else if (params.terraform_action == 'destroy') {

                            sh """
                                export AWS_DEFAULT_REGION=${AWS_REGION}

                                terraform -chdir=${TERRAFORM_DIR} destroy \
                                -var="environment=${params.environment}" \
                                -auto-approve
                            """
                        }

                    }

                }
            }
        }

    }

    post {

        success {
            echo "Terraform ${params.terraform_action} completed successfully for ${params.MODULE}"
        }

        failure {
            echo "Terraform pipeline failed."
        }

        //always {
            //cleanWs()
        //}
    }
}
